# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/yc7330/Custom-Vitis-IP-for-Tiled-GEMM/vivado/gemm_bd/gemm_bd.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0.xci
# IP: The module: 'design_1_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yc7330/Custom-Vitis-IP-for-Tiled-GEMM/vivado/gemm_bd/gemm_bd.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/yc7330/Custom-Vitis-IP-for-Tiled-GEMM/vivado/gemm_bd/gemm_bd.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/yc7330/Custom-Vitis-IP-for-Tiled-GEMM/vivado/gemm_bd/gemm_bd.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/yc7330/Custom-Vitis-IP-for-Tiled-GEMM/vivado/gemm_bd/gemm_bd.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0.xci
# IP: The module: 'design_1_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yc7330/Custom-Vitis-IP-for-Tiled-GEMM/vivado/gemm_bd/gemm_bd.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/yc7330/Custom-Vitis-IP-for-Tiled-GEMM/vivado/gemm_bd/gemm_bd.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/yc7330/Custom-Vitis-IP-for-Tiled-GEMM/vivado/gemm_bd/gemm_bd.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
